### ISSUE TITLE
Parse Dashboard can only be remotely accessed via HTTPS

### ISSUE THREAD

**Issue by jamesbrinsley** [cherukumilli/parse-dashboard-example#1]
I have deployed the dashboard to Heroku manually, however I am getting the following message when trying to access the dashboard.

"Parse Dashboard can only be remotely accessed via HTTPS"

**Comment by mauriciord** [comment]
Same here

**Comment by cherukumilli** [comment]
@jamesbrinsley @mauriciord 
I have been running the app locally. I didn't get a chance to deploy it to heroku yet.

parse-dashboard github repo has the following to say:
https://github.com/ParsePlatform/parse-dashboard#security-considerations

### Security Considerations

In order to securely deploy the dashboard without leaking your apps master key, you will need to use HTTPS and Basic Authentication.

The deployed dashboard detects if you are using a secure connection. If you are deploying the dashboard behind a load balancer or proxy that does early SSL termination, then the app won't be able to detect that the connection is secure. In this case, you can start the dashboard with the `--allowInsecureHTTP=1` option. You will then be responsible for ensuring that your proxy or load balancer only allows HTTPS.

_I haven't tried this yet but will give it a shot later today_
